<?php require_once($_SERVER['DOCUMENT_ROOT'].'/_assets/inc/head.php'); // HTTP head?>
<?php require_once($_SERVER['DOCUMENT_ROOT'].'/_assets/inc/navigation.php'); //navigation?>

<section id="mast">
	
	<img src="/_assets/img/header-ttte.jpg" alt="current Tennessee Tech Tuba Ensemble photo" title="current Tennessee Tech Tuba Ensemble photo">

</section><!--mast-->

<section id="main" class="ttte">

	<div class="inner">
	
		<h1>The Tennessee Tech Tuba Ensemble’s 48th season</h1>
			
		<h2>Euphoniums:</h2>

		<h3>Guy Bortz, <span>Kingsport, TN</span></h3>
		<h3>Mary Tallman, <span>Bristol, VA</span></h3>
		<h3>Cody Dailey, <span>Murfreesboro, TN</span></h3>
		<h3>Tyler Thurber, <span>Shelbyville, TN</span></h3>
		<h3>Michael Engelhart, <span>Sweetwater, TN</span></h3>
		<h3>Jordan Watkins, <span>Bolivar, TN</span></h3>
		<h3>Justin Gorodetzky, <span>White House, TN</span></h3>
		<h3>Amanda Werlein, <span>Tullahoma, TN</span></h3>
		<h3>Wimberly Hall, <span>Hixson, TN</span></h3>
		<h3>Robert Wormsley, <span>Signal Mountain, TN</span></h3>
		<h3>Adam Mullican, <span>Hermitage, TN</span></h3>

		<h2 class="multiple">Tubas:</h2>

		<h3>Austin Cooper, <span>Mt. Juliet, TN</span></h3>
		<h3>John Paul Powers, <span>Clinton, TN</span></h3>
		<h3>Caleb Davidson, <span>Tullahoma, TN</span></h3>
		<h3>Travis Roberson, <span>Church Hill, TN</span></h3>
		<h3>Ashanti Demas, <span>Locus Grove, VA</span></h3>
		<h3>Ryan Snell, <span>Charleston, SC</span></h3>
		<h3>Nolan Derrick, <span>Church Hill, TN</span></h3>
		<h3>Jalen Talley, <span>Huntsville, AL</span></h3>
		<h3>Curtiss Hoeppner, <span>Lake Charles, LA</span></h3>
		<h3>Quinton Webber, <span>Clinton, TN</span></h3>
		<h3>Josh Maberry, <span>Oak Ridge, TN</span></h3>
		<h3>Ottie West, <span>Smyrna, TN</span></h3>
		<h3>Lincoln Myers, <span>Tullahoma, TN</span></h3>
		<h3>Aaron Whitfield, <span>Blountville, TN</span></h3>

		<h4>“…responsible for the composition and arrangement of more music for the tuba than any other single source…”</h4>

		<p>The Tennessee Technological University Tuba Ensemble recently celebrated their 40th year of performances and recording activity.  The ensemble has been selected by The Tennessee Board of Regents to receive the prestigious TBR Academic Excellence and Quality Award.  The TTTE is the first music program in the state of Tennessee to receive this award.  Additionally, the ensemble has been notified that their latest three CD recording releases, CARNEGIE VI, a documentation of their sixth appearance at Carnegie Hall in New York City, EUPHONIUMS UNLIMITED and PHAT BOTTOM TUBAS on the Mark Records label were submitted and accepted by the National Academy of Recording Arts and Sciences (NARAS) to be included on their “Grammy Entry List”.</p>

		<p>The internationally acclaimed Tennessee Tech Tuba Ensemble (TTTE) from Tennessee Technological University in Cookeville, Tennessee, is considered the “pioneer” ensemble of its kind.  The TTTE is continually received with favor by audiences from Carnegie Hall in New York to Jackson Square in New Orleans.  The group has been described as one that is “not a novelty, but an ensemble with a unique sound.”   The TTTE has received the highest accolades from the professional world of tubists and euphoniumists, music educators, and professional reviewers.  Following the example of the TTTE, similar groups have formed all over the world.  Music generated by and for the Tech ensemble has been performed in Japan, Australia, Canada, all over Western Europe, and throughout the United States.</p>

		<p>Organized in 1967 by the present conductor, R. Winston Morris, the TTTE was the birth of a new concept in music for multiple tubas. Previous to this, there had been a very limited amount of activity involving chamber music for tubas.  The Tech ensemble introduced the idea of the large tuba/euphonium choir with parts being frequently doubled.  Needless to say, there was a total lack of literature for such an ensemble; therefore, the Tech group had to commence an extensive “search” for music. That “search” has led to the composition and arrangement of over one thousand works specifically done for the Tech ensemble by outstanding composers from the United States and abroad.</p>

		<p>The TTTE first appeared in Carnegie Recital Hall in 1976 and continues, with their unprecedented seventh appearance of the Alumni All-Star Ensemble in January 2007, to be the only tuba ensemble to ever present full concerts on that world famous stage.</p>

		<p>Performances by the TTTE have been presented from New York to Chicago, from Florida to Texas, and almost everywhere in between. Appearances have been made at regional and national Music Educators National Conference (MENC) workshops; regional, national, and international Tubists Universal Brotherhood Association (T.U.B.A.) workshops; the New Orleans Jazz Festival, Preservation Hall, and Mardi Gras Parades; the 1984 International Brass Congress; Disney World; Kennedy Center and the Smithsonian Institute in Washington, D.C.; the Spoleto Festival; TV work for PM Magazine and annual PBS productions; and the world's fairs in Knoxville, Tennessee, and New Orleans, Louisiana.</p>

		<p>The TTTE was the first ensemble of its kind to release a commercially produced record album.  Since that first recording in 1975, over twenty TTTE recordings have been produced. Performances, commissioning programs, participation in regional, national, and international workshops, and conferences and recordings by the TTTE have expanded opportunities for tubists and euphoniumists and provided the music world with a new and exciting sound.</p>

	</div><!--inner-->

</section><!--main-->

<?php require_once($_SERVER['DOCUMENT_ROOT'].'/_assets/inc/footer.php'); // footer, close body and html?>